export const SET_COMPANY_EMPLOYEES = '@sproud/ADMIN/SET_COMPANY_EMPLOYEES'
export const SET_COMPANY_DEPARTMENTS = '@sproud/ADMIN/SET_COMPANY_DEPARTMENTS'

export const START_ADMIN_LOADING = '@sproud/ADMIN/START_ADMIN_LOADING'
export const SUCCESS_ADMIN_LOADING = '@sproud/ADMIN/SUCCESS_ADMIN_LOADING'
export const FAILURE_ADMIN_LOADING = '@sproud/ADMIN/FAILURE_ADMIN_LOADING'
