export const SET_OVERALL_BUDGET = '@sproud/BUDGET/SET_OVERALL_BUDGET'
export const GET_SPENDINGS = '@sproud/BUDGET/GET_SPENDINGS'

export const START_FETCHING_BUDGET = '@sproud/BUDGET/START_FETCHING_BUDGET'
export const SUCCESS_FETCHING_BUDGET = '@sproud/BUDGET/SUCCESS_FETCHING_BUDGET'
export const FAILURE_FETCHING_BUDGET = '@sproud/BUDGET/FAILURE_FETCHING_BUDGET'
