export const SET_RECOMMENDED_TRAININGS = '@sproud/TRAINING/SET_RECOMMENDED_TRAININGS'
export const SET_UPCOMING_TRAININGS = '@sproud/TRAINING/SET_UPCOMING_TRAININGS'
export const SET_TRAININGS_FOR_DEPARTMENT = '@sproud/TRAINING/SET_TRAININGS_FOR_DEPARTMENT'

export const START_FETCHING_TRAININGS = '@sproud/TRAINING/START_FETCHING_TRAININGS'
export const SUCCESS_FETCHING_TRAININGS = '@sproud/TRAINING/SUCCESS_FETCHING_TRAININGS'
export const FAILURE_FETCHING_TRAININGS = '@sproud/TRAINING/FAILURE_FETCHING_TRAININGS'
