apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.service.image }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Values.service.image | quote }}
      {{- if ne $.Values.environment "io" }}
      feature: {{ $.Values.service.tag | quote }}
      {{- else }}
      tag: {{ $.Values.service.tag | quote }}
      {{- end }}
  template:
    metadata:
      labels:
        app: {{ $.Values.service.image | quote }}
        {{- if ne $.Values.environment "io" }}
        feature: {{ $.Values.service.tag | quote }}
        {{- else }}
        tag: {{ $.Values.service.tag | quote }}
        {{- end }}
    spec:
      containers:
      - name: {{ $.Values.service.image }}-service
        image: ghcr.io/getsproud/{{ $.Values.service.image }}:{{ $.Values.service.tag }}
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            {{- if eq $.Values.nodeEnv "development" }}
            port: 3000
            {{- else }}
            port: 80
            {{- end }}
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            {{- if eq $.Values.nodeEnv "development" }}
            port: 3000
            {{- else }}
            port: 80
            {{- end }}
          initialDelaySeconds: 60
          periodSeconds: 10
        ports:
        {{- if eq $.Values.nodeEnv "development" }}
        - containerPort: 3000
          protocol: TCP
        {{- else }}
        - containerPort: 80
          protocol: TCP
        {{- end }}
        env:
        - name: NODE_ENV
          value: {{ $.Values.nodeEnv }}
      imagePullSecrets:
      - name: gh-registry
---
