apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $.Values.service.image | quote }}
    {{- if and (ne $.Values.environment "io") (contains "rc-" $.Values.service.tag) }}
    feature: stage
    {{- else if ne $.Values.environment "io" }}
    feature: {{ $.Values.service.tag | quote }}
    {{- else }}
    tag: {{ $.Values.service.tag | quote }}
    {{- end }}
  name: {{ $.Values.service.image }}-service
spec:
  ports:
  - name: http
    port: 80
    {{- if eq $.Values.nodeEnv "development" }}
    targetPort: 3000
    {{- else }}
    targetPort: 80
    {{- end }}
  selector:
    app: {{ $.Values.service.image | quote }}
    {{- if and (ne $.Values.environment "io") (contains "rc-" $.Values.service.tag) }}
    feature: stage
    {{- else if ne $.Values.environment "io" }}
    feature: {{ $.Values.service.tag | quote }}
    {{- else }}
    tag: {{ $.Values.service.tag | quote }}
    {{- end }}
---
