apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $.Values.service.image }}
    {{- if ne $.Values.environment "io" }}s
    feature: {{ trunc 1 $.Values.subdomain | quote }}
    {{- else }}
    tag: {{ $.Values.service.tag }}
    {{- end }}
  name: {{ $.Values.service.image }}-service
spec:
  ports:
  - name: http
    port: 80
    {{- if eq $.Values.nodeEnv "stage" }}
    targetPort: 80
    {{- else }}
    targetPort: 3000
    {{- end }}
  selector:
    app: {{ $.Values.service.image }}
    {{- if ne $.Values.environment "io" }}s
    feature: {{ trunc 1 $.Values.subdomain | quote }}
    {{- else }}
    tag: {{ $.Values.service.tag }}
    {{- end }}
---
